version: "3.9"
name: desafio-conecthus
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001" # websockets
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://app:app@postgres:5432/app?schema=public
      REDIS_URL: redis://redis:6379
      MQTT_URL: mqtt://mqtt:1883
      PORT: 3000
    depends_on:
      - postgres
      - redis
      - mqtt
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://backend:3000
      VITE_MQTT_WS_URL: ws://mqtt:9001
    depends_on:
      - backend
    ports:
      - "5173:5173"

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    environment:
      EXPO_PUBLIC_API_URL: http://backend:3000
      EXPO_PUBLIC_MQTT_WS_URL: ws://mqtt:9001
    depends_on:
      - backend

volumes:
  pgdata:
  mosquitto_data:
  mosquitto_log:


